version: 1.0.{build}

image: Visual Studio 2017

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\smela

shallow_clone: true

matrix:
    fast_finish: false

install:
    - cmd: echo "Downloading conan..."
    - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
    - cmd: pip.exe install conan
    - cmd: conan user # Create the conan data directory

platform:
    - x64

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc14

before_build:
    - cmd: conan --version
    - cmd: cmake --version

build_script:
    - cd scripts
    - build-msvc14-%PLATFORM%-%CONFIGURATION%
