image: Visual Studio 2017

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\smela
shallow_clone: true

matrix:
    fast_finish: false

platform:
    - x64

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc14
        - TOOLCHAIN: msvc15

build_script:
    - cd scripts
    - chmod +x build-$CC-$TARGET_CPU-$BUILD_CONFIGURATION
    - ./build-$CC-$TARGET_CPU-$BUILD_CONFIGURATION
