version: 1.0.{build}

image:
    - Visual Studio 2015
    - Visual Studio 2017

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\smela

shallow_clone: true

matrix:
    fast_finish: false

install:
    - cmd: echo "Downloading conan..."
    - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
    - cmd: pip.exe install conan
    # Create the conan data directory.
    - cmd: conan user

platform:
    - x64

configuration:
    - Debug
    - Release

before_build:
    - cmd: conan --version
    - cmd: cmake --version
    - ps: |
        Write-Output "$env:APPVEYOR_JOB_NAME"
        if ("$env:APPVEYOR_JOB_NAME" -match "Image: Visual Studio 2015") {
            $env:generator="Visual Studio 14 2015"
            $env:vs_version="14"
        } else {
            $env:generator="Visual Studio 15 2017"
            $env:vs_version="15"
        }
        if ($env:PLATFORM -eq "x64") {
            $env:generator="$env:generator Win64"
        }
        Write-Output generator="$env:generator"
        Write-Output vs_version="$env:vs_version"

        Write-Output "Creating a build directory..."
        (mkdir build) -and (cd build)

        Write-Output "[Conan] Downloading packages..."
        conan install .. `
            --build missing `
            -s build_type=$env:CONFIGURATION `
            -s compiler="Visual Studio" `
            -s compiler.version=$env:vs_version

        Write-Output "[CMake] Generating the project..."
        cmake .. -G "$env:generator"

build_script:
    - cmake --build . --config %CONFIGURATION% -- /m /v:minimal
