dist: trusty
sudo: required

language: cpp

os:
    - osx
    - linux

compiler:
    - clang
    - gcc

env:
    - TARGET_CPU=x64 BUILD_CONFIGURATION=debug
    - TARGET_CPU=x64 BUILD_CONFIGURATION=release

matrix:
    exclude:
        - os: osx
          compiler: gcc

install:
    - pip install conan
    - conan user

before_script:
    - uname -a
    - printenv
    - which clang++
    - clang++ --version 2>&1 | grep clang
    - which g++
    - g++ --version
    - $CXX --version

script:
    - cd scripts
    - chmod +x build-$COMPILER-$TARGET_CPU-$BUILD_CONFIGURATION
    - ./build-$COMPILER-$TARGET_CPU-$BUILD_CONFIGURATION
