dist: trusty
sudo: required

language: cpp

os:
    - osx
    - linux

compiler:
    - clang
    - gcc

env:
    - COMPILER=clang TARGET_CPU=x64 BUILD_CONFIGURATION=debug
    - COMPILER=clang TARGET_CPU=x64 BUILD_CONFIGURATION=release
    - COMPILER=gcc TARGET_CPU=x64 BUILD_CONFIGURATION=debug
    - COMPILER=gcc TARGET_CPU=x64 BUILD_CONFIGURATION=release

matrix:
    exclude:
        - os: osx
          compiler: gcc

install:
    - pip install conan
    - conan user

script:
    - cd scripts
    - chmod +x build-$COMPILER-$TARGET_CPU-$BUILD_CONFIGURATION
    - ./build-$COMPILER-$TARGET_CPU-$BUILD_CONFIGURATION
