language: cpp

dist: trusty
sudo: required
group: edge

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

# Use Linux unless specified otherwise.
os: linux

matrix:
  include:
    #
    # Clang on OSX.
    #

    # XCode 8.3
    - env: COMPILER=clang++ BUILD_TYPE=Debug CONAN_COMPILER=clang CONAN_COMPILER_VERSION=8.1
      os: osx
      osx_image: xcode8.3
      compiler: clang

    - env: COMPILER=clang++ BUILD_TYPE=Release CONAN_COMPILER=clang CONAN_COMPILER_VERSION=8.1
      os: osx
      osx_image: xcode8.3
      compiler: clang

    # XCode 9.1
    - env: COMPILER=clang++ BUILD_TYPE=Debug CONAN_COMPILER=clang CONAN_COMPILER_VERSION=9.0
      os: osx
      osx_image: xcode9.1
      compiler: clang

    - env: COMPILER=clang++ BUILD_TYPE=Release CONAN_COMPILER=clang CONAN_COMPILER_VERSION=9.0
      os: osx
      osx_image: xcode9.1
      compiler: clang

    #
    # GCC on Linux.
    #

    - env: COMPILER=g++-5 BUILD_TYPE=Debug CONAN_COMPILER=gcc CONAN_COMPILER_VERSION=5.4
      addons: &gcc5
        apt:
          packages: g++-5
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-5 BUILD_TYPE=Release CONAN_COMPILER=gcc CONAN_COMPILER_VERSION=5.4
      addons: *gcc5

  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

install:
  # Install conan.
  #- sudo pip install --user conan
  # Automatic detection of your arch, compiler, etc.
  #- conan user

  # Set the ${CXX} variable properly.
  - export CXX=${COMPILER}
  - ${CXX} --version

  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/.
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"

  # Install a recent CMake (unless already installed on OS X).
  - CMAKE_VERSION=3.7.2
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      sudo pip install conan
      conan user
    else
      brew install cmake || brew upgrade cmake
      brew update
      brew install conan
      conan user
    fi

before_script:
  - conan --version
  - cmake --version
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir -p build && cd build
  - |
    conan install .. \
      --build missing \
      -s build_type=${BUILD_TYPE} \
      -s compiler=${CONAN_COMPILER} \
      -s compiler.version=${CONAN_COMPILER_VERSION}

  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - cmake --build . -- -j2
