language: cpp

dist: trusty
sudo: required
group: edge

matrix:
  include:

    #
    # Clang on macOS.
    #

    # Xcode 7.3.
    - env: CXX_COMPILER=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode7.3
      compiler: clang

    - env: CXX_COMPILER=clang++ BUILD_TYPE=Release
      os: osx
      osx_image: xcode7.3
      compiler: clang

    # Xcode 8.0.
    - env: CXX_COMPILER=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode8.0
      compiler: clang

    - env: CXX_COMPILER=clang++ BUILD_TYPE=Release
      os: osx
      osx_image: xcode8.0
      compiler: clang

    # Xcode 8.1.
    - env: CXX_COMPILER=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode8.1
      compiler: clang

    - env: CXX_COMPILER=clang++ BUILD_TYPE=Release
      os: osx
      osx_image: xcode8.1
      compiler: clang

    # Xcode 8.2.
    - env: CXX_COMPILER=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode8.2
      compiler: clang

    - env: CXX_COMPILER=clang++ BUILD_TYPE=Release
      os: osx
      osx_image: xcode8.2
      compiler: clang

    # Xcode 8.3.
    - env: CXX_COMPILER=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode8.3
      compiler: clang

    - env: CXX_COMPILER=clang++ BUILD_TYPE=Release
      os: osx
      osx_image: xcode8.3
      compiler: clang

    # Xcode 9.0.
    - env: CXX_COMPILER=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode9.0
      compiler: clang

    - env: CXX_COMPILER=clang++ BUILD_TYPE=Release
      os: osx
      osx_image: xcode9.0
      compiler: clang

    # Xcode 9.1.
    - env: CXX_COMPILER=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode9.1
      compiler: clang

    - env: CXX_COMPILER=clang++ BUILD_TYPE=Release
      os: osx
      osx_image: xcode9.1
      compiler: clang

    #
    # GCC on Linux.
    #

    # GCC 5.
    - env: CXX_COMPILER=g++-5 CC_COMPILER=gcc-5 BUILD_TYPE=Debug
      os: linux
      addons: &gcc5
        apt:
          packages: g++-5
          sources: ubuntu-toolchain-r-test

    - env: CXX_COMPILER=g++-5 CC_COMPILER=gcc-5 BUILD_TYPE=Release
      os: linux
      addons: *gcc5

    # GCC 6.
    - env: CXX_COMPILER=g++-6 CC_COMPILER=gcc-6 BUILD_TYPE=Debug
      os: linux
      addons: &gcc6
        apt:
          packages: g++-6
          sources: ubuntu-toolchain-r-test

    - env: CXX_COMPILER=g++-6 CC_COMPILER=gcc-6 BUILD_TYPE=Release
      os: linux
      addons: *gcc6

    # GCC 7.
    - env: CXX_COMPILER=g++-7 CC_COMPILER=gcc-7 BUILD_TYPE=Debug
      os: linux
      addons: &gcc7
        apt:
          packages: g++-7
          sources: ubuntu-toolchain-r-test

    - env: CXX_COMPILER=g++-7 CC_COMPILER=gcc-7 BUILD_TYPE=Release
      os: linux
      addons: *gcc7

  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

install:
  # Set the ${CXX} variable properly.
  - export CXX=${CXX_COMPILER}
  - ${CXX} --version
  # Set the ${CC} variable properly.
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      export CC=${CC_COMPILER}
      ${CC} --version
    fi

  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/.
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"

  # Install a recent CMake (unless already installed on macOS) and Conan.
  - CMAKE_VERSION=3.9.5
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      sudo pip install conan
    else
      brew update
      brew install cmake || brew upgrade cmake
      brew install conan || brew upgrade conan
    fi

before_script:
  - conan --version
  - cmake --version
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir -p build && cd build
  - conan install .. --build missing -s build_type=${BUILD_TYPE}
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - cmake --build . --config ${BUILD_TYPE}
