language: cpp

dist: trusty
sudo: required
group: edge

matrix:
  include:

    #
    # Clang on OSX.
    #

    # XCode 8.3
    - env: COMPILER=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode8.3
      compiler: clang

    - env: COMPILER=clang++ BUILD_TYPE=Release
      os: osx
      osx_image: xcode8.3
      compiler: clang

install:
  # Set the ${CXX} variable properly.
  - export CXX=${COMPILER}
  - ${CXX} --version

  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/.
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"

  # Install a recent CMake (unless already installed on OS X) and Conan.
  - CMAKE_VERSION=3.7.2
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      sudo pip install conan
    else
      brew install cmake || brew upgrade cmake
      brew install conan || brew upgrade conan
    fi

before_script:
  - conan --version
  - cmake --version
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir -p build && cd build
  - conan install .. --build missing -s build_type=${BUILD_TYPE}
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - cmake --build . -- config ${BUILD_TYPE}
