dist: trusty
sudo: required

language: cpp

os:
    - osx

compiler:
    - clang

env:
    - TARGET_CPU=x64 BUILD_CONFIGURATION=debug
    - TARGET_CPU=x64 BUILD_CONFIGURATION=release

matrix:
    exclude:
        - os: osx
          compiler: gcc

        - os: osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

        - os: osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

script:
    - cd scripts
    - chmod +x build-clang-$TARGET_CPU-$BUILD_CONFIGURATION
    - ./build-clang-$TARGET_CPU-$BUILD_CONFIGURATION
