dist: trusty
sudo: required

language: cpp

os:
    - osx
    - linux

compiler:
    - clang
    - gcc

env:
    - TARGET_CPU=x64 BUILD_CONFIGURATION=debug
    - TARGET_CPU=x64 BUILD_CONFIGURATION=release

matrix:
    exclude:
        - os: osx
          compiler: gcc
        - os: linux
          compiler: clang

install:
    # Install conan.
    - sudo pip install conan
    # Automatic detection of your arch, compiler, etc.
    - conan user

before_script:
    - clang++ --version 2>&1 | grep clang
    - g++ --version

script:
    - cd scripts
    - chmod +x build-$CC-$TARGET_CPU-$BUILD_CONFIGURATION
    - ./build-$CC-$TARGET_CPU-$BUILD_CONFIGURATION
